version: '3'

services:
  frontend:
    build:
      context: ./frontend/Car-parking-react-frontend
    image: frontend-app
    container_name: frontcarpark
    depends_on:
      - app_api
    networks:
      - frontend
      - backend
    ports:
      - "7001:80"
  frontendAdmin:
    build:
      context: ./frontend/admin-page
    image: frontend-app-admin
    container_name: frontcarpark-admin
    depends_on:
      - app_api
    networks:
      - frontendAdmin
      - backend
    ports:
      - "7007:80"
  app_api:
    build:
      context: ./backend/RestService/
    image: car-park 
    container_name: backcarpark
    ports:
      - "8080:8080" 
    networks: 
      - backend
    depends_on: 
      - postgres       
  postgres:
    image: postgres
    container_name: car-parking-db
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demodb
   # volumes:
   #   - /postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks: 
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: dataui
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped
    networks: 
      - backend

volumes:
  postgres-data:

networks: 
  backend:
  frontend:
  frontendAdmin:
